// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Password_manager.Repo;

#nullable disable

namespace Password_manager.Migrations
{
    [DbContext(typeof(VaultContext))]
    [Migration("20241004205929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Password_manager.Entities.PasswordHash", b =>
                {
                    b.Property<string>("HashedPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeySalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HashedPassword");

                    b.ToTable("Password");
                });

            modelBuilder.Entity("Password_manager.Entities.VaultItem", b =>
                {
                    b.Property<byte[]>("Data")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Data");

                    b.ToTable("Vault");
                });
#pragma warning restore 612, 618
        }
    }
}
