// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Password_manager.Repo;

#nullable disable

namespace Password_manager.Migrations
{
    [DbContext(typeof(VaultContext))]
    partial class VaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Password_manager.Entities.PasswordHash", b =>
                {
                    b.Property<string>("HashedPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeySalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HashedPassword");

                    b.ToTable("Password");
                });

            modelBuilder.Entity("Password_manager.Entities.VaultItem", b =>
                {
                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Data");

                    b.ToTable("Vault");
                });
#pragma warning restore 612, 618
        }
    }
}
